### ISSUE TITLE
Document rules used in the plugin

### ISSUE THREAD

**Issue by alecxe** [Nate-Wilkins/eslint-plugin-bdd#1]
This would really make potential plugin users better understand what kind of functionality the plugin provides. Thanks.

**Comment by Nate-Wilkins** [comment]
@alecxe That's disappointing... sorry about that. Working on docs now.

**Comment by Nate-Wilkins** [comment]
Fixed with https://github.com/Nate-Wilkins/eslint-plugin-bdd/commit/a7c0d232986082e693f55205a4edc3e61f3b4c8c
