### ISSUE TITLE
Support jasmine's focus keywords

### ISSUE THREAD

**Issue by andrey-skl** [Nate-Wilkins/eslint-plugin-bdd#2]
Only describe: fdescribe, 
Only one test: fit

iit, ddescribe is dropped from jasmine https://github.com/karma-runner/karma-jasmine/issues/73

**Comment by Nate-Wilkins** [comment]
Nice catch! Looks like we need to update the docs though to include this though.

**Comment by andrey-skl** [comment]
@Nate-Wilkins yeah, thank you.

**Comment by Nate-Wilkins** [comment]
@huston007 no thank you!

**Comment by andrey-skl** [comment]
@Nate-Wilkins please publish update to NPM then)

**Comment by Nate-Wilkins** [comment]
Updated as 1.1.1
