### ISSUE TITLE
bdd/focus error for methods which starts wtih fit

### ISSUE THREAD

**Issue by ArtZanko** [Nate-Wilkins/eslint-plugin-bdd#4]
Hello!

We are using eslint-plugin-bdd and since ver1.1.1 we have errors which doesn't associated with test files.
For example, if we have something like `foo.fitSomething()` eslint-plugin-bdd find it like focus keyword and show `error  Expected to find no focus tests  bdd/focus`.

**Comment by Nate-Wilkins** [comment]
@ArtZanko With the release of 2.0.0 there shouldn't be an issue with "custom" testing functions. Was a dumb feature anyways :+1: 

Let me know if you still have issues!

**Comment by ArtZanko** [comment]
Everything is ok. Thanks!
